# Generated by Django 5.2.7 on 2025-10-20 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Closed', max_length=20)),
                ('priority', models.CharField(choices=[('4 - Low', '4 - Low'), ('3 - Medium', '3 - Medium'), ('2 - High', '2 - Medium'), ('1 - Critical', '1 - Medium')], max_length=20)),
                ('category', models.CharField(choices=[('kegagalan proses', 'kegagalan proses'), ('event monitoring', 'event monitoring'), ('eod production', 'eod production'), ('transaction', 'transaction'), ('tidak bisa dilakukan', 'tidak bisa dilakukan'), ('drop', 'drop'), ('cannot access', 'cannot access'), ('tidak dapat login', 'tidak dapat login'), ('penjelasan detail sebuah transaksi', 'penjelasan detail sebuah transaksi'), ('application', 'application'), ('hardware', 'hardware')], max_length=50)),
                ('open_date', models.DateTimeField()),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('time_left_incl_on_hold', models.FloatField()),
                ('item', models.CharField(max_length=100)),
                ('is_sla_violated', models.BooleanField(default=False)),
                ('is_open_date_off', models.CharField(choices=[('Hari Kerja', 'Hari Kerja'), ('Hari Libur', 'Hari Libur')], max_length=20)),
                ('is_due_date_off', models.CharField(choices=[('Hari Kerja', 'Hari Kerja'), ('Hari Libur', 'Hari Libur')], max_length=20)),
                ('days_to_due', models.IntegerField()),
                ('open_month', models.IntegerField()),
                ('application_creation_day_of_week', models.CharField(max_length=20)),
                ('application_creation_hour', models.IntegerField()),
                ('application_sla_deadline_day_of_week', models.CharField(max_length=20)),
                ('application_sla_deadline_hour', models.IntegerField()),
                ('resolution_duration', models.FloatField()),
                ('total_tickets_resolved_wc', models.FloatField()),
                ('sla_threshold', models.FloatField()),
                ('average_resolution_time_ac', models.FloatField()),
                ('sla_to_average_resolution_ratio_rc', models.FloatField()),
                ('application_sla_compliance_rate', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Tickets',
                'ordering': ['-open_date'],
            },
        ),
    ]
